version: '3.4'

services:

  rabbitmq:
    image: 'pcloud/rabbitmq-stomp'
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      RABBITMQ_ERLANG_COOKIE:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
    env_file:
      - .env
    networks:
      - elastic

  redis:
    container_name: redis
    image: redis:7.0.8
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD --port 6379"
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "network.host=0.0.0.0"
      - "http.host=0.0.0.0"
      - "transport.host=0.0.0.0"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /home/ubuntu/data:/usr/share/elasticsearch/data
    networks:
      - elastic

  app:
    image: sunju5402/seatchoice
    container_name: seatchoice
    ports:
      - "8081:8080"
    depends_on:
      - redis
    restart: always

networks:
  elastic:
    driver: bridge