spring:
  profiles:
    include: secret

  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  # 이미지 용량
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jwt:
    token:
      secret-key:

  redis:
    host:
    port:
    password:

  #S3
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static:
    s3:
      bucket:
    stack:
      auto: false

oauth:
  kakao:
    client-id:
    redirect-uri:
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me