spring:
  profiles:
    include: secret
    active: local

  datasource:
    url:
    driver-class-name:
    username:
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  # 이미지 용량
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jwt:
    token:
      secret-key:

  redis:
    host:
    port:
    password:

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
            client-secret:
            client-name: Kakao
            client-authentication-method: POST
            redirect-uri:
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

  #S3
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
       static:
    s3:
      bucket:
    stack:
      auto: false

elasticsearch:
  host:
  port:

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace

kopis:
  api:
    url:
    key:

