spring:
  profiles:
    include: secret
    active: local

  datasource:
    url:
    driver-class-name:
    username:
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  # 이미지 용량
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jwt:
    token:
      secret-key:

  #S3
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
       static:
    s3:
      bucket:
    stack:
      auto: false

oauth:
  kakao:
    client-id:
    redirect-uri:
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

elasticsearch:
  host:
  port:
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace

kopis:
  api:
    url:
    key: