spring:
  profiles:
    include: secret
    active: local

  datasource:
    url:
    driver-class-name:
    username:
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  # 이미지 용량
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jwt:
    token:
      secret-key:

  redis:
    host:
    port:
    password:

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
            client-secret:
            redirect-uri:
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            scope:
              - profile_nickname
              - account_email
            clientName: Kakao
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

  #S3
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
       static:
    s3:
      bucket:
    stack:
      auto: false

elasticsearch:
  host:
  port:

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace

kopis:
  api:
    url:
    key:

cors:
  allowed-origins:
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

token:
  auth:
    tokenSecret:
    tokenExpiry:
    refreshTokenExpiry:
  oauth2:
    authorizedRedirectUris:
